# Generated by Django 3.1.4 on 2021-01-18 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20210118_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='time',
            field=models.TimeField(),
        ),
    ]
