# Generated by Django 3.1.4 on 2021-01-18 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20210118_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='fees',
            name='description',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='fees',
            name='student',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='portal.students'),
        ),
        migrations.AlterField(
            model_name='fees',
            name='dueDate',
            field=models.DateField(),
        ),
    ]
