# Generated by Django 3.1.4 on 2021-01-18 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_auto_20210118_1319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='datOfBirth',
            new_name='datofBirth',
        ),
    ]
