# Generated by Django 3.1.4 on 2021-01-20 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_auto_20210118_1340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='course',
        ),
    ]
