# Generated by Django 3.1.4 on 2021-01-24 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_remove_students_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='level',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='courseName',
            field=models.CharField(max_length=1000),
        ),
    ]
