# Generated by Django 3.1.4 on 2021-01-24 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_auto_20210124_1104'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Courses',
            new_name='Course',
        ),
    ]
