# Generated by Django 3.1.4 on 2021-01-24 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_auto_20210124_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='course',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='portal.course'),
        ),
    ]
