# Generated by Django 3.1.4 on 2021-01-24 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_students_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='course',
        ),
    ]
