# Generated by Django 3.1.4 on 2021-01-24 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0013_students_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='course',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.course'),
        ),
    ]
